FROM node:22-alpine AS frontend-build

WORKDIR /frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

RUN npm run build


FROM nginx:1.27.2

COPY --from=frontend-build /frontend/dist /usr/share/nginx/html

COPY infra/nginx.conf /etc/nginx/nginx.conf